### ISSUE TITLE
All The Mods 7 Incompatability?

### ISSUE THREAD

**Issue by MrKioFlow** [MelanX/ToolSwap#27]
Adjusting config settings, digging around, not sure, but the mod switches AWAY from the tool it is supposed to be using, enchanted, used, whatever, or not. 

Digging dirt with hand, stays hand. Dig dirt with shovel, switches to hand. Same for stone, wood, anything. Tools are in the hotbar. 

Please advise, really want this mod :3

Just using the latest version of All The Mods 7, only added optifine additionally.

**Comment by MelanX** [comment]
How much durability does the tool have? If only 1 left, you should disable the config option for that. If other, please tell me which tools you used and I try to reproduce the behavior.

**Comment by MrKioFlow** [comment]
This is the start of a new world, so I am no where near mid/late game. I am talking stone/wood vanilla tools. And no, not switching away from 1 use left tools, brand new or not it still switches away from the tools.

Also I noticed, maybe it's related, that my game crashes upon new world creation too. I intially had a save, played it a bit, installed this mod, and found the issue. After a little while I deleted the save and created a new one, in which the game would hang on the new world creation screen and then ask if I would like to start in safe mode disabling any data packs, but I never included any data packs to begin with.

**Comment by MelanX** [comment]
It would be good to have one of these crash reports.
*If you don't know how to provide logs/crash reports: Use a website like `pastebin.com`/`gist.com` or something similar to this.*

**Comment by Samsterious** [comment]
ATM7 has Immersive Engineering, which is a mod I have noticed causes this same behavior just by being loaded into the game. I would encourage you to share whether temporarily disabling that mod makes the problem go away (it would greatly reduce the breadth of this issue to know that).

**Comment by ochotonida** [comment]
This issue can be reproduced in 1.18 using only Artifacts and Automatic Tool Swap (https://github.com/ochotonida/artifacts/issues/127).

What seems to be causing this issue is that Automatic Tool Swap doesn't take into consideration that blocks may have multiple 'mineable/<tool>' tags. Instead, it will use the first matching tag it finds (if any).
https://github.com/MelanX/ToolSwap/blob/e167431ba543670d45f81bae7fe4e50a97f63bfa/src/main/java/de/melanx/toolswap/ClientToolSwap.java#L247-L249
Artifacts adds the ['artifacts:mineable/digging_claws'](https://github.com/ochotonida/artifacts/blob/3632767f755a7679d2b99729f0387fcb05d6e8e2/src/generated/resources/data/artifacts/tags/blocks/mineable/digging_claws.json) block tag that contains pretty much all blocks, and has no corresponding tools. When Automatic Tool Swap tries to find matching tools in the hotbar using this tag it doesn't find any, causing it to default to the first non-damageable item in the hotbar instead.

**Comment by MelanX** [comment]
Thank you for your help!
